-- Backfilled from DB migration history
CREATE INDEX IF NOT EXISTS idx_domain_verifications_page_id ON domain_verifications (page_id);
CREATE INDEX IF NOT EXISTS idx_draft_folders_account_group_id ON draft_folders (account_group_id);
CREATE INDEX IF NOT EXISTS idx_draft_folders_user_id ON draft_folders (user_id);
CREATE INDEX IF NOT EXISTS idx_engagement_pods_owner_id ON engagement_pods (owner_id);
CREATE INDEX IF NOT EXISTS idx_inbox_assignments_assigned_by ON inbox_assignments (assigned_by);
CREATE INDEX IF NOT EXISTS idx_media_folders_workspace_id ON media_folders (workspace_id);
CREATE INDEX IF NOT EXISTS idx_pod_engagements_member_id ON pod_engagements (member_id);
CREATE INDEX IF NOT EXISTS idx_pod_members_user_id ON pod_members (user_id);
CREATE INDEX IF NOT EXISTS idx_pod_posts_member_id ON pod_posts (member_id);
CREATE INDEX IF NOT EXISTS idx_pod_posts_pod_id ON pod_posts (pod_id);
CREATE INDEX IF NOT EXISTS idx_post_templates_account_group_id ON post_templates (account_group_id);
CREATE INDEX IF NOT EXISTS idx_post_templates_user_id ON post_templates (user_id);
CREATE INDEX IF NOT EXISTS idx_post_templates_workspace_id ON post_templates (workspace_id);
CREATE INDEX IF NOT EXISTS idx_product_catalogs_ig_account_id ON product_catalogs (ig_account_id);
CREATE INDEX IF NOT EXISTS idx_product_tags_post_id ON product_tags (post_id);
CREATE INDEX IF NOT EXISTS idx_watermark_configs_account_group_id ON watermark_configs (account_group_id);
CREATE INDEX IF NOT EXISTS idx_watermark_configs_user_id ON watermark_configs (user_id);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_subscription_id ON webhook_deliveries (subscription_id);
