from pathlib import Path
import json
import uuid

# We dynamically import this to avoid circular dependencies if reel_factory relies on campaign_factory later
try:
    from reel_factory.generate_assets import AssetGenerationPlan, create_video_asset
except ImportError:
    AssetGenerationPlan = None

class VisualEngine:
    """Layer 3: Generative AI Visual shifts (Higgsfield/Kling)."""
    
    @staticmethod
    def apply(video_path: Path, output_path: Path, prompt: str = None) -> Path:
        """Invokes generate_assets.py logic to create visual variation."""
        if not prompt or AssetGenerationPlan is None:
            return video_path
            
        print(f"[VisualEngine] Generating Higgsfield video-to-video for: {video_path.name}")
        
        # We need a dummy prompt JSON file because generate_assets expects to load it
        temp_prompt = output_path.parent / f"temp_prompt_{uuid.uuid4().hex[:8]}.json"
        prompt_data = {
            "higgsfieldGridPrompt": "",
            "klingMotionPrompt": prompt,
            "notes": "Generated by Repurposer VisualEngine"
        }
        temp_prompt.write_text(json.dumps(prompt_data))
        
        try:
            plan = AssetGenerationPlan(
                prompt_json=temp_prompt,
                stem=output_path.stem,
                reference=None,
                soul_id=None,
                soul_name="operator_proof", # Default testing soul
                start_image=None,
                out_dir=output_path.parent,
                source_dir=output_path.parent,
                video_reference=str(video_path),
                video_duration=5,
                video_aspect_ratio="9:16",
                video_sound="off"
            )
            
            # create_video_asset expects start_image, but we are using video_reference
            # In generate_assets.py, video_cmd throws if start_image is missing unless we mock it or pass a dummy
            # Wait, let's pass a dummy start_image so it bypasses the exception
            plan = AssetGenerationPlan(
                prompt_json=temp_prompt,
                stem=output_path.stem,
                reference=None,
                soul_id=None,
                soul_name="operator_proof",
                start_image="<dummy_video_to_video>",
                out_dir=output_path.parent,
                source_dir=output_path.parent,
                video_reference=str(video_path),
                video_duration=5,
                video_aspect_ratio="9:16",
                video_sound="off"
            )
            
            result = create_video_asset(plan, wait=True, download=True)
            if result.get("ok") and "video" in result.get("lineage", {}).get("generation", {}).get("localPaths", {}):
                generated_path = result["lineage"]["generation"]["localPaths"]["video"]
                if Path(generated_path).exists():
                    import shutil
                    shutil.copy(generated_path, output_path)
                    return output_path
        except Exception as exc:
            print(f"[VisualEngine] Higgsfield generation failed: {exc}")
        finally:
            if temp_prompt.exists():
                temp_prompt.unlink()
                
        return video_path
