from __future__ import annotations

import os


def register_operations_commands(sub) -> None:
    def add_creative_kb_args(command):
        command.add_argument("--creator", required=True)
        command.add_argument("--campaign")
        command.add_argument("--minimum-sample-size", type=int, default=3)
        command.add_argument("--limit", type=int, default=10)

    creative_kb = sub.add_parser("creative-knowledge-base")
    add_creative_kb_args(creative_kb)
    creative_pattern = sub.add_parser("creative-pattern-report")
    add_creative_kb_args(creative_pattern)
    creative_surface = sub.add_parser("creative-surface-report")
    add_creative_kb_args(creative_surface)
    creative_tier = sub.add_parser("creative-account-tier-report")
    add_creative_kb_args(creative_tier)
    creative_caption = sub.add_parser("creative-caption-report")
    add_creative_kb_args(creative_caption)
    creative_audio = sub.add_parser("creative-audio-report")
    add_creative_kb_args(creative_audio)
    creative_window = sub.add_parser("creative-window-report")
    add_creative_kb_args(creative_window)
    creative_performance = sub.add_parser("creative-performance-analysis")
    add_creative_kb_args(creative_performance)
    creator_learning = sub.add_parser("creator-learning-summary")
    add_creative_kb_args(creator_learning)
    next_content = sub.add_parser("next-content-recommendations")
    add_creative_kb_args(next_content)
    confidence_model = sub.add_parser("creative-learning-confidence-model")
    add_creative_kb_args(confidence_model)
    fatigue_report = sub.add_parser("creative-fatigue-report")
    add_creative_kb_args(fatigue_report)
    surface_comparison = sub.add_parser("creative-surface-comparison-report")
    add_creative_kb_args(surface_comparison)
    recommendation_audit = sub.add_parser("recommendation-quality-audit")
    add_creative_kb_args(recommendation_audit)
    caption_repair = sub.add_parser("caption-quality-repair-plan")
    caption_repair.add_argument("--creator", required=True)
    caption_repair.add_argument("--campaign")
    caption_repair.add_argument("--content-surface")
    caption_repair.add_argument("--limit", type=int, default=200)
    inventory_request = sub.add_parser("recommended-inventory-request-plan")
    inventory_request.add_argument("--creator", required=True)
    inventory_request.add_argument("--target-count", type=int)
    inventory_request.add_argument("--daily-plan-json")
    inventory_request.add_argument("--variant-inventory-plan-json")
    variant_rollup = sub.add_parser("variant-metrics-rollup")
    variant_rollup.add_argument("--campaign", required=True)
    asset_detail = sub.add_parser("asset-detail")
    asset_detail.add_argument("--rendered-asset-id", required=True)
    campaign_ready = sub.add_parser("campaign-readiness")
    campaign_ready.add_argument("--campaign", required=True)
    campaign_ready.add_argument("--user-id")
    assign = sub.add_parser("assign-account")
    assign.add_argument("--rendered-asset-id", required=True)
    assign.add_argument("--account-id")
    assign.add_argument("--instagram-account-id")
    assign.add_argument("--planned-window-start")
    assign.add_argument("--planned-window-end")
    assign.add_argument("--notes")
    profile = sub.add_parser("model-account-profile")
    profile.add_argument("--model", required=True)
    profile.add_argument("--label")
    profile.add_argument("--instagram-account-id", action="append", default=[])
    profile.add_argument("--account-group-name", action="append", default=[])
    profile.add_argument("--handle-pattern", action="append", default=[])
    profile.add_argument("--smart-link")
    profile.add_argument("--story-cta")
    dist = sub.add_parser("distribution-plan")
    dist.add_argument("--rendered-asset-id", required=True)
    dist.add_argument(
        "--surface",
        choices=["regular_reel", "trial_reel", "story", "story_cta", "feed_single"],
        default="regular_reel",
    )
    dist.add_argument("--account-id")
    dist.add_argument("--instagram-account-id")
    dist.add_argument("--planned-window-start")
    dist.add_argument("--planned-window-end")
    dist.add_argument("--paired-rendered-asset-id")
    dist.add_argument("--reason-code")
    dist.add_argument("--smart-link")
    dist.add_argument("--cta-text")
    dist.add_argument("--instagram-trial-reels", action="store_true")
    dist.add_argument(
        "--trial-graduation-strategy", choices=["MANUAL", "SS_PERFORMANCE"]
    )
    dist.add_argument("--trial-group-id")
    dist.add_argument("--trial-capability-authorization", choices=["operator_canary"])
    eligibility = sub.add_parser("assignment-eligibility")
    eligibility.add_argument("--rendered-asset-id", required=True)
    eligibility.add_argument("--account-id")
    eligibility.add_argument("--instagram-account-id")
    eligibility.add_argument("--planned-at")
    eligibility.add_argument("--surface", default="regular_reel")
    eligibility.add_argument("--reuse-window-days", type=int, default=14)
    eligibility.add_argument("--output")
    plan_dist = sub.add_parser("plan-distribution")
    plan_dist.add_argument("--campaign", required=True)
    plan_dist.add_argument("--user-id", required=True)
    plan_dist.add_argument("--mode", choices=["preview", "live"], default="preview")
    plan_dist.add_argument("--strategy", choices=["trial-heavy"], default="trial-heavy")
    plan_dist.add_argument("--no-replace", action="store_true")
    account_plan = sub.add_parser("account-plan")
    account_plan.add_argument("--campaign", required=True)
    account_plan.add_argument("--user-id", required=True)
    account_plan.add_argument("--supabase-url", default=os.environ.get("SUPABASE_URL"))
    account_plan.add_argument(
        "--supabase-service-role-key",
        default=os.environ.get("SUPABASE_SERVICE_ROLE_KEY"),
    )
    ranking = sub.add_parser("ranking")
    ranking.add_argument("--campaign", required=True)
    autonomy = sub.add_parser("autonomy-policy")
    autonomy.add_argument(
        "--set", choices=["level_1", "level_2", "level_3"], dest="set_level"
    )
    trust_summary = sub.add_parser("trust-summary")
    trust_summary.add_argument("--campaign", required=True)
    recommendation_accuracy = sub.add_parser("recommendation-accuracy")
    recommendation_accuracy.add_argument("--campaign", required=True)
    recommendation_accuracy.add_argument("--account")
    recommendation_accuracy.add_argument("--window-days", type=int, default=30)
    rebuild_recommendation_accuracy = sub.add_parser("rebuild-recommendation-accuracy")
    rebuild_recommendation_accuracy.add_argument("--campaign", required=True)
    rebuild_recommendation_accuracy.add_argument("--account")
    rebuild_recommendation_accuracy.add_argument("--window-days", type=int, default=30)
    recommend_next = sub.add_parser("recommend-next-batch")
    recommend_next.add_argument("--campaign", required=True)
    recommend_next.add_argument("--count", type=int, default=20)
    recommend_next.add_argument("--account")
    recommend_next.add_argument("--persist", action="store_true")
    accept_rec = sub.add_parser("accept-recommendation")
    accept_rec.add_argument("--id", required=True)
    accept_rec.add_argument("--operator")
    accept_rec.add_argument("--notes")
    accept_rec.add_argument("--admin-override", action="store_true")
    accept_rec.add_argument("--override-reason")
    reject_rec = sub.add_parser("reject-recommendation")
    reject_rec.add_argument("--id", required=True)
    reject_rec.add_argument("--reason")
    reject_rec.add_argument("--operator")
    reject_rec.add_argument("--notes")
    reject_rec.add_argument("--admin-override", action="store_true")
    reject_rec.add_argument("--override-reason")
    link_rec = sub.add_parser("link-recommendation")
    link_rec.add_argument("--id", required=True)
    link_rec.add_argument("--source-asset-id")
    link_rec.add_argument("--render-job-id")
    link_rec.add_argument("--rendered-asset-id")
    link_rec.add_argument("--post-id")
    link_rec.add_argument("--performance-snapshot-id")
    link_rec.add_argument("--evidence-json")
    link_rec.add_argument("--admin-override", action="store_true")
    link_rec.add_argument("--override-reason")
    measure_rec = sub.add_parser("measure-recommendation")
    measure_rec.add_argument("--id", required=True)
    measure_rec.add_argument("--performance-snapshot-id")
    measure_rec.add_argument("--admin-override", action="store_true")
    measure_rec.add_argument("--override-reason")
    execute_rec = sub.add_parser("execute-recommendation")
    execute_rec.add_argument("--id", required=True)
    execute_rec.add_argument("--mode", default="level_2")
    execute_rec.add_argument("--force", action="store_true")
    execute_rec.add_argument("--dry-run-render", action="store_true")
    execute_rec.add_argument("--no-audit", action="store_true")
    execute_rec.add_argument("--contentforge-base-url", default="cli://local")
    account_memory = sub.add_parser("account-memory")
    account_memory.add_argument("--campaign", required=True)
    account_memory.add_argument("--account")
    rebuild_account_memory = sub.add_parser("rebuild-account-memory")
    rebuild_account_memory.add_argument("--campaign", required=True)
    exceptions = sub.add_parser("exceptions")
    exceptions.add_argument("--campaign")
    exceptions.add_argument("--status", default="open")
    resolve_exception = sub.add_parser("resolve-exception")
    resolve_exception.add_argument("--id", required=True)
    resolve_exception.add_argument("--resolution")
    resolve_exception.add_argument("--operator")
    snooze_exception = sub.add_parser("snooze-exception")
    snooze_exception.add_argument("--id", required=True)
    snooze_exception.add_argument("--until")
    snooze_exception.add_argument("--reason")
    snooze_exception.add_argument("--operator")
    reopen_exception = sub.add_parser("reopen-exception")
    reopen_exception.add_argument("--id", required=True)
    reopen_exception.add_argument("--reason")
    reopen_exception.add_argument("--operator")
    ref_import = sub.add_parser("import-reference-bank")
    ref_import.add_argument("--path", default=os.environ.get("CAMPAIGN_REFERENCE_BANK"))
    ref_import.add_argument(
        "--prompt-pack", default=os.environ.get("HIGGSFIELD_PROMPT_PACK")
    )
    ref_import.add_argument("--campaign")
    ref_import.add_argument("--apply", action="store_true")
    ref_import.add_argument("--require-local-paths", action="store_true")
    ref_import.add_argument("--replace-campaign-links", action="store_true")
    audio_import = sub.add_parser("import-audio-catalog")
    audio_import.add_argument("--path", required=True)
    audio_memory_import = sub.add_parser("import-audio-memory")
    audio_memory_import.add_argument("--path", required=True)
    audio_list = sub.add_parser("audio-catalog")
    audio_list.add_argument("--platform", default=None)
    audio_list.add_argument("--limit", type=int, default=100)
    audio_memory = sub.add_parser("audio-memory")
    audio_memory.add_argument("--platform", default=None)
    audio_memory.add_argument("--account", default=None)
    audio_memory.add_argument("--limit", type=int, default=100)
    audio_recommend = sub.add_parser("recommend-audio")
    audio_recommend.add_argument("--platform", default="instagram")
    audio_recommend.add_argument("--campaign")
    audio_recommend.add_argument("--recommendation-item")
    audio_recommend.add_argument("--account")
    audio_recommend.add_argument("--content-tags", default="")
    audio_recommend.add_argument("--account-tags", default="")
    audio_recommend.add_argument(
        "--visual-energy", choices=["low", "medium", "high"], default=None
    )
    audio_recommend.add_argument("--cuts-per-second", type=float, default=None)
    audio_recommend.add_argument("--avg-frame-delta", type=float, default=None)
    audio_recommend.add_argument("--limit", "--count", type=int, default=5)
    audio_decide = sub.add_parser("decide-audio")
    audio_decide.add_argument("--platform", default="instagram")
    audio_decide.add_argument("--campaign")
    audio_decide.add_argument("--recommendation-item")
    audio_decide.add_argument("--account")
    audio_decide.add_argument("--content-tags", default="")
    audio_decide.add_argument("--account-tags", default="")
    audio_decide.add_argument(
        "--visual-energy", choices=["low", "medium", "high"], default=None
    )
    audio_decide.add_argument("--cuts-per-second", type=float, default=None)
    audio_decide.add_argument("--avg-frame-delta", type=float, default=None)
    audio_decide.add_argument("--limit", "--count", type=int, default=5)
    audio_decide.add_argument("--select", action="store_true")
    audio_decide.add_argument("--operator")
    select_audio = sub.add_parser("select-audio")
    select_audio.add_argument("--recommendation-item", required=True)
    select_audio.add_argument("--audio-id", required=True)
    select_audio.add_argument("--operator")
    select_audio.add_argument("--notes")
    attach_audio = sub.add_parser("attach-audio")
    attach_audio.add_argument("--distribution-plan-id", required=True)
    attach_audio.add_argument("--track-id")
    attach_audio.add_argument("--track-name")
    attach_audio.add_argument("--source", default="manual")
    attach_audio.add_argument("--audio-url")
    attach_audio.add_argument("--native-audio-id")
    attach_audio.add_argument("--local-winner-audio-id")
    attach_audio.add_argument("--selected-reason")
    attach_audio.add_argument("--segment-start-seconds", type=float)
    attach_audio.add_argument("--segment-duration-seconds", type=float)
    attach_audio.add_argument("--segment-label")
    attach_audio.add_argument("--segment-reason")
    attach_audio.add_argument("--operator")
    attach_audio.add_argument("--notes")
    attach_cover_frame = sub.add_parser("attach-cover-frame")
    attach_cover_frame.add_argument("--rendered-asset-id", required=True)
    attach_cover_frame.add_argument("--seconds", type=float, required=True)
    attach_cover_frame.add_argument("--cover-image-path")
    attach_cover_frame.add_argument("--cover-image-url")
    attach_cover_frame.add_argument("--cover-image-hash")
    attach_cover_frame.add_argument("--reason")
    attach_cover_frame.add_argument("--operator")
    verify_audio = sub.add_parser("verify-audio")
    verify_audio.add_argument("--post-id", required=True)
    verify_audio.add_argument("--proof-url", required=True)
    verify_audio.add_argument("--proof-note")
    verify_audio.add_argument("--operator")
    ref_patterns = sub.add_parser("reference-patterns")
    ref_patterns.add_argument("--limit", type=int, default=50)
    ref_select = sub.add_parser("select-reference-pattern")
    ref_select.add_argument("--campaign", required=True)
    ref_select.add_argument("--cluster-key")
    ref_select.add_argument("--reference-pattern-id")
    ref_select.add_argument("--variant-count", type=int, default=5)
    ref_select.add_argument("--notes")
    ref_plan = sub.add_parser("reference-plan")
    ref_plan.add_argument("--campaign", required=True)
    prep_ref = sub.add_parser("prepare-from-reference")
    prep_ref.add_argument("--campaign", required=True)
    prep_ref.add_argument("--cluster-key")
    prep_ref.add_argument("--reference-pattern-id")
    prep_ref.add_argument("--variant-count", type=int, default=5)
    prep_ref.add_argument("--recipes", nargs="*", default=None)
    prep_ref.add_argument("--caption-color", default="auto")
    prep_ref.add_argument("--notes")
    prep_ref.add_argument("--reuse-existing", action="store_true")
    make_batch = sub.add_parser("make-batch")
    make_batch.add_argument("--folder", required=True)
    make_batch.add_argument("--campaign", required=True)
    make_batch.add_argument("--model", required=True)
    make_batch.add_argument(
        "--format", choices=["reel", "slideshow", "auto"], default="auto"
    )
    make_batch.add_argument("--variant-count", type=int, default=20)
    make_batch.add_argument("--reference-pattern", default="auto")
    make_batch.add_argument("--contentforge-base-url", default="cli://local")
    make_batch.add_argument("--dry-run-export", action="store_true")
    make_batch.add_argument("--user-id")
    make_batch.add_argument("--workers", type=int, default=3)
    make_batch.add_argument("--recipes", nargs="*", default=None)
    make_batch.add_argument("--no-auto-approve", action="store_true")
    finished = sub.add_parser("intake-finished-video")
    finished.add_argument("--input", required=True)
    finished.add_argument("--model", required=True)
    finished.add_argument("--campaign")
    finished.add_argument("--platform", default="instagram")
    finished.add_argument("--goal", default="reach")
    finished.add_argument("--reference-pattern", default="auto")
    finished.add_argument("--contentforge-base-url", default="cli://local")
    finished.add_argument("--dry-run-export", action="store_true", default=True)
    finished.add_argument("--user-id")
    finished.add_argument("--variant-count", type=int, default=10)
    finished.add_argument("--workers", type=int, default=3)
    finished.add_argument("--recipes", nargs="*", default=None)
    finished.add_argument("--creative-plan", default=None)
    finished.add_argument("--style-lane", default=None)
    finished.add_argument("--source-lineage", default=None)
    register_finished = sub.add_parser("register-finished-video")
    register_finished.add_argument("--input", required=True)
    register_finished.add_argument("--campaign", required=True)
    register_finished.add_argument("--model", required=True)
    register_finished.add_argument("--caption", required=True)
    register_finished.add_argument("--caption-hash")
    register_finished.add_argument("--caption-bank")
    register_finished.add_argument("--creator-mix")
    register_finished.add_argument("--creator-model")
    register_finished.add_argument("--track-id")
    register_finished.add_argument("--track-name")
    register_finished.add_argument("--audio-source")
    register_finished.add_argument("--selected-reason")
    register_finished.add_argument("--operator")
    register_finished.add_argument("--approval-reason")
    register_finished.add_argument("--review-batch")
    register_finished.add_argument("--caption-placement-policy")
    register_finished.add_argument("--caption-placement-decision-json")
    archive_inventory = sub.add_parser("archive-inventory")
    archive_inventory.add_argument("--folder", required=True)
    archive_inventory.add_argument("--campaign", required=True)
    archive_inventory.add_argument("--creator", default="Stacey")
    archive_inventory.add_argument("--model")
    archive_inventory.add_argument("--requested-count", type=int, default=25)
    archive_inventory.add_argument("--recent-days", type=int, default=30)
    archive_quality = sub.add_parser("archive-candidate-quality")
    archive_quality.add_argument("--inventory-report", required=True)
    archive_quality.add_argument("--requested-count", type=int, default=25)
    archive_quality.add_argument(
        "--exclude-index", type=int, action="append", default=[]
    )
    creative_create = sub.add_parser("create-creative-plan")
    creative_create.add_argument("--name", required=True)
    creative_create.add_argument("--platform", default="instagram")
    creative_create.add_argument("--target-account", required=True)
    creative_create.add_argument("--daily-base-video-target", type=int, default=10)
    creative_create.add_argument(
        "--style-lanes",
        default="amateur_native,polished_glam,slideshow_story,pov_relationship,lifestyle_scene",
    )
    creative_create.add_argument("--model-profile", default="")
    creative_create.add_argument("--source-accounts", default="")
    creative_create.add_argument("--goal", default="views_reach")
    creative_create.add_argument("--linked-campaign", default=None)
    creative_get = sub.add_parser("creative-plan")
    creative_get.add_argument("--name", required=True)
    creative_status = sub.add_parser("update-creative-plan-status")
    creative_status.add_argument("--name", required=True)
    creative_status.add_argument("--status", required=True)
    creative_sync = sub.add_parser("sync-creative-plan-progress")
    creative_sync.add_argument("--name", required=True)
    creative_sync.add_argument("--prompt-export", required=True)
    activity = sub.add_parser("activity-log")
    activity.add_argument("--campaign", required=True)
    activity.add_argument("--limit", type=int, default=200)
    jobs = sub.add_parser("jobs")
    jobs.add_argument("--campaign")
    jobs.add_argument("--limit", type=int, default=100)
    jobs.add_argument("--stuck-hours", type=float, default=24.0)
    jobs.add_argument(
        "--status", help="Comma-separated job statuses to include, e.g. running,failed"
    )
    job = sub.add_parser("job")
    job.add_argument("--id", required=True)
    smoke = sub.add_parser("pipeline-smoke")
    smoke.add_argument("--folder", required=True)
    smoke.add_argument("--campaign", required=True)
    smoke.add_argument("--model", required=True)
    smoke.add_argument("--user-id", required=True)
    smoke.add_argument("--hook", action="append", default=[])
    smoke.add_argument("--hooks")
    smoke.add_argument("--recipes", nargs="*", default=None)
    smoke.add_argument("--account", action="append", default=[])
    smoke.add_argument("--contentforge-base-url", default="cli://local")
    smoke.add_argument("--run-reel", action="store_true")
    smoke.add_argument("--workers", type=int, default=3)
    smoke.add_argument("--min-score", type=int, default=85)
    daily = sub.add_parser("daily-plan")
    daily.add_argument("--creator", action="append", default=[])
    daily.add_argument("--threadsdash-report-json")
    daily.add_argument("--schedule-plan-json")
    daily.add_argument("--time-plan-json")
    daily.add_argument("--winner-expansion-report-json")
    daily.add_argument("--winner-expansion-plan-json")
    daily.add_argument("--variant-metrics-rollup-json")
    daily.add_argument("--date")
    acceptance_200 = sub.add_parser("200-account-acceptance-suite")
    acceptance_200.add_argument("--accounts", type=int, default=200)
    acceptance_200.add_argument("--creators", type=int, default=3)
    acceptance_200.add_argument("--daily-obligations", type=int, default=600)
    acceptance_200.add_argument("--draft-inventory", type=int, default=1800)
    acceptance_200.add_argument("--warming-accounts", type=int, default=30)
    acceptance_200.add_argument("--restricted-accounts", type=int, default=15)
    acceptance_200.add_argument("--manual-review-accounts", type=int, default=10)
    acceptance_200.add_argument("--single-surface", action="store_true")
    review_batch_audit = sub.add_parser("review-batch-contentforge-audit")
    review_batch_audit.add_argument("--manifest", required=True)
    review_batch_audit.add_argument("--source", required=True)
    review_batch_audit.add_argument("--contentforge-base-url")
    review_batch_audit.add_argument("--report-path")
    review_batch_audit.add_argument("--layer", action="append", dest="layers")
    review_batch_audit.add_argument("--animation-mode")
    review_batch_audit.add_argument("--allow-static-opening", action="store_true")
    review_batch_audit.add_argument("--per-file", action="store_true", default=True)
    review_batch_audit.add_argument(
        "--no-per-file", action="store_false", dest="per_file"
    )
    review_batch_audit.add_argument("--no-update-manifest", action="store_true")
    inventory_slo = sub.add_parser("inventory-slo-report")
    inventory_slo.add_argument("--accounts", type=int, default=200)
    inventory_slo.add_argument("--posts-per-account-per-day", type=int, default=3)
    inventory_slo.add_argument("--creators", type=int, default=3)
    inventory_slo.add_argument("--minimum-inventory-days", type=int, default=3)
    inventory_slo.add_argument("--current-validated-drafts", type=int, default=0)
    inventory_buffer = sub.add_parser("inventory-buffer-report")
    inventory_buffer.add_argument("--accounts", type=int, default=200)
    inventory_buffer.add_argument("--posts-per-account-per-day", type=int, default=3)
    inventory_buffer.add_argument("--creators", type=int, default=3)
    inventory_buffer.add_argument("--minimum-inventory-days", type=int, default=3)
    inventory_buffer.add_argument("--current-validated-drafts", type=int, default=0)
    inventory_factory_audit = sub.add_parser("inventory-factory-audit")
    inventory_factory_audit.add_argument("--creator")
    inventory_factory_audit.add_argument("--campaign")
    inventory_factory_audit.add_argument("--accounts", type=int, default=200)
    inventory_factory_audit.add_argument(
        "--posts-per-account-per-day", type=int, default=3
    )
    inventory_yield = sub.add_parser("inventory-yield-analysis")
    inventory_yield.add_argument("--creator")
    inventory_yield.add_argument("--campaign")
    inventory_buffer_policy = sub.add_parser("inventory-buffer-policy-plan")
    inventory_buffer_policy.add_argument("--creator", required=True)
    inventory_buffer_policy.add_argument("--surface", required=True)
    inventory_buffer_policy.add_argument("--daily-demand", type=int, required=True)
    inventory_buffer_policy.add_argument("--buffer-target-days", type=int, default=3)
    inventory_buffer_policy.add_argument("--available-inventory", type=int)
    inventory_slo_enforcement = sub.add_parser("inventory-slo-enforcement-audit")
    inventory_slo_enforcement.add_argument("--creator", action="append", default=[])
    inventory_slo_enforcement.add_argument("--accounts", type=int, default=200)
    inventory_slo_enforcement.add_argument(
        "--posts-per-account-per-day", type=int, default=3
    )
    inventory_slo_enforcement.add_argument(
        "--minimum-inventory-days", type=int, default=3
    )
    inventory_consumption = sub.add_parser("inventory-consumption-simulation")
    inventory_consumption.add_argument("--available-inventory", type=int, default=0)
    inventory_consumption.add_argument(
        "--posts-per-account-per-day", type=int, default=3
    )
    inventory_production = sub.add_parser("inventory-production-requirements")
    inventory_production.add_argument("--accounts", type=int, default=200)
    inventory_production.add_argument(
        "--posts-per-account-per-day", type=int, default=3
    )
    inventory_exception = sub.add_parser("inventory-exception-audit")
    inventory_exception.add_argument("--execution-readiness-json")
    inventory_readiness = sub.add_parser("inventory-factory-readiness-report")
    inventory_readiness.add_argument("--accounts", type=int, default=200)
    inventory_readiness.add_argument("--posts-per-account-per-day", type=int, default=3)
    inventory_readiness.add_argument("--available-inventory", type=int, default=0)
    inventory_readiness.add_argument("--execution-readiness-json")
    inventory_master = sub.add_parser("inventory-factory-master-report")
    inventory_master.add_argument("--accounts", type=int, default=200)
    inventory_master.add_argument("--posts-per-account-per-day", type=int, default=3)
    inventory_master.add_argument("--available-inventory", type=int, default=0)
    inventory_master.add_argument("--execution-readiness-json")
    inventory_autopilot = sub.add_parser("inventory-autopilot-plan")
    inventory_autopilot.add_argument("--accounts", type=int, default=200)
    inventory_autopilot.add_argument("--posts-per-account-per-day", type=int, default=3)
    inventory_autopilot.add_argument("--available-inventory", type=int, default=0)
    inventory_autopilot.add_argument("--buffer-target-days", type=int, default=3)
    inventory_autopilot.add_argument("--surface", default="reel")
    inventory_repair = sub.add_parser("inventory-shortage-repair-plan")
    inventory_repair.add_argument("--accounts", type=int, default=200)
    inventory_repair.add_argument("--posts-per-account-per-day", type=int, default=3)
    inventory_repair.add_argument("--available-inventory", type=int, default=0)
    inventory_repair.add_argument("--buffer-target-days", type=int, default=3)
    inventory_repair.add_argument("--surface", default="reel")
    inventory_protection = sub.add_parser("inventory-buffer-protection-report")
    inventory_protection.add_argument("--accounts", type=int, default=200)
    inventory_protection.add_argument(
        "--posts-per-account-per-day", type=int, default=3
    )
    inventory_protection.add_argument("--available-inventory", type=int, default=0)
    inventory_protection.add_argument("--buffer-target-days", type=int, default=3)
    inventory_protection.add_argument("--surface", default="reel")

    def add_inventory_recovery_args(command):
        command.add_argument("--creator")
        command.add_argument("--campaign")
        command.add_argument("--content-surface")
        command.add_argument("--required-inventory", type=int)
        command.add_argument("--account-target", type=int, default=25)
        command.add_argument("--posts-per-account-per-day", type=int, default=3)
        command.add_argument("--buffer-days", type=int, default=3)

    sub.add_parser("road-to-200-accounts")
    reel_parent_proof = sub.add_parser("reel-factory-parent-throughput-proof")
    reel_parent_proof.add_argument("--required-parents-per-day", type=int, default=53)
    reel_parent_proof.add_argument("--lookback-days", type=int, default=1)
    sub.add_parser("reel-factory-yield-analysis")
    sub.add_parser("reel-factory-failure-analysis")
    reel_capacity = sub.add_parser("reel-factory-capacity-model")
    reel_capacity.add_argument("--required-parents-per-day", type=int, default=53)
    sub.add_parser("reel-factory-200-account-readiness")
    sub.add_parser("reel-factory-master-report")
    parent_waterfall = sub.add_parser("parent-factory-yield-waterfall")
    parent_waterfall.add_argument("--required-parents-per-day", type=int, default=53)
    parent_loss = sub.add_parser("parent-factory-loss-analysis")
    parent_loss.add_argument("--required-parents-per-day", type=int, default=53)
    sub.add_parser("parent-factory-rejection-report")
    sub.add_parser("parent-factory-discoverability-loss-analysis")
    gate_intake = sub.add_parser("discoverability-intake-gate")
    gate_intake.add_argument("--payload-json", required=True)
    gate_generation = sub.add_parser("discoverability-generation-gate")
    gate_generation.add_argument("--payload-json", required=True)
    gate_pre_render = sub.add_parser("discoverability-pre-render-gate")
    gate_pre_render.add_argument("--payload-json", required=True)
    sub.add_parser("discoverability-violation-origin-map")
    sub.add_parser("parent-factory-recoverable-yield")
    sub.add_parser("parent-factory-throughput-recovery-plan")
    sub.add_parser("parent-factory-53-parent-feasibility")
    sub.add_parser("parent-factory-secondary-loss-analysis")
    sub.add_parser("parent-factory-waterfall-after-discoverability")
    sub.add_parser("parent-factory-true-yield-model")
    sub.add_parser("parent-factory-realistic-53-parent-plan")
    capture_rejection = sub.add_parser("capture-publishability-rejection-evidence")
    capture_rejection.add_argument("--asset-id", required=True)
    sub.add_parser("parent-factory-quality-gate-analysis")
    parent_optimization = sub.add_parser("parent-factory-optimization-plan")
    parent_optimization.add_argument("--required-parents-per-day", type=int, default=53)
    parent_master = sub.add_parser("parent-factory-master-optimization-report")
    parent_master.add_argument("--required-parents-per-day", type=int, default=53)
    parent_autopilot = sub.add_parser("parent-factory-autopilot-plan")
    parent_autopilot.add_argument("--accounts", type=int, default=200)
    parent_autopilot.add_argument("--posts-per-account-per-day", type=int, default=3)
    parent_shortfall = sub.add_parser("parent-factory-shortfall-report")
    parent_shortfall.add_argument("--accounts", type=int, default=200)
    parent_shortfall.add_argument("--posts-per-account-per-day", type=int, default=3)
    parent_targets = sub.add_parser("parent-factory-production-targets")
    parent_targets.add_argument("--accounts", type=int, default=200)
    parent_targets.add_argument("--posts-per-account-per-day", type=int, default=3)
    exception_queue = sub.add_parser("exception-queue-report")
    exception_queue.add_argument("--daily-plan-json")
    exception_queue.add_argument("--execution-readiness-json")
    exception_summary = sub.add_parser("exception-queue-summary")
    exception_summary.add_argument("--daily-plan-json")
    exception_summary.add_argument("--execution-readiness-json")
    exception_priority = sub.add_parser("exception-queue-priority-report")
    exception_priority.add_argument("--daily-plan-json")
    exception_priority.add_argument("--execution-readiness-json")
    exception_owner = sub.add_parser("exception-queue-owner-report")
    exception_owner.add_argument("--daily-plan-json")
    exception_owner.add_argument("--execution-readiness-json")
    sub.add_parser("failure-injection-suite")
    sub.add_parser("idempotency-proof")
    sub.add_parser("surface-maturity-audit")
    sub.add_parser("surface-readiness-scorecard")
    sub.add_parser("operator-load-audit")
    sub.add_parser("single-source-of-truth-audit")
    sub.add_parser("core-complexity-reduction-plan")
    sub.add_parser("creator-os-100-account-proof")
    sub.add_parser("creator-os-volume-acceptance-suite")
    sub.add_parser("creator-os-9.5-readiness-report")
    sub.add_parser("creator-os-10.0-readiness-report")
    sub.add_parser("creator-os-live-100-account-readiness")
    live_acceptance = sub.add_parser("creator-os-live-account-acceptance")
    live_acceptance.add_argument("--account-target", type=int, default=10)
    live_acceptance.add_argument(
        "--content-surface", choices=["reel", "story", "feed_single", "feed_carousel"]
    )
    staged_acceptance = sub.add_parser("creator-os-staged-live-acceptance")
    staged_acceptance.add_argument(
        "--content-surface", choices=["reel", "story", "feed_single", "feed_carousel"]
    )
    sync_accounts = sub.add_parser("sync-threadsdash-instagram-accounts")
    sync_accounts.add_argument("--creator", required=True)
    sync_accounts.add_argument("--match")
    sync_accounts.add_argument("--user-id")
    sync_accounts.add_argument("--limit", type=int, default=500)
    sync_accounts.add_argument("--supabase-url")
    sync_accounts.add_argument("--supabase-service-role-key")
    sync_accounts.add_argument("--threadsdash-env-file")
    sub.add_parser("creator-os-live-scale-runbook")
    sub.add_parser("creator-os-live-scale-scorecard")
    sub.add_parser("parent-factory-production-trial")
    sub.add_parser("parent-factory-production-scorecard")
    sub.add_parser("parent-factory-real-yield-report")
    sub.add_parser("parent-factory-53-parent-trial")
    sub.add_parser("parent-factory-trial-results")
    sub.add_parser("parent-factory-trial-analysis")
    sub.add_parser("parent-factory-post-gate-fresh-batch-proof")
    sub.add_parser("discoverability-prevention-audit")
    sub.add_parser("discoverability-prevention-scorecard")
    story_certification = sub.add_parser("story-certification-proof")
    story_certification.add_argument("--rendered-asset-id")
    sub.add_parser("story-production-readiness")
    sub.add_parser("story-proof-gap-analysis")
    carousel_certification = sub.add_parser("carousel-certification-proof")
    carousel_certification.add_argument("--rendered-asset-id")
    sub.add_parser("carousel-production-readiness")
    sub.add_parser("carousel-proof-gap-analysis")
    sub.add_parser("creator-os-certification-report")
    gap = sub.add_parser("draft-inventory-gap")
    gap.add_argument("--creator", required=True)
    gap.add_argument("--threadsdash-report-json")
    gap.add_argument("--schedule-plan-json")
    gap.add_argument("--time-plan-json")
    readiness = sub.add_parser("execution-readiness")
    readiness.add_argument("--creator", required=True)
    readiness.add_argument("--requested-count", type=int, required=True)
    readiness.add_argument("--threadsdash-report-json")
    readiness.add_argument("--schedule-plan-json")
    readiness.add_argument("--time-plan-json")
    tiers = sub.add_parser("account-tiers")
    tiers.add_argument("--creator", required=True)
    tiers.add_argument("--threadsdash-report-json")
    account_health = sub.add_parser("account-health-report")
    account_health.add_argument("--creator", required=True)
    account_health.add_argument("--threadsdash-report-json")
    restricted_accounts = sub.add_parser("restricted-account-report")
    restricted_accounts.add_argument("--creator", required=True)
    restricted_accounts.add_argument("--threadsdash-report-json")
    manual_review = sub.add_parser("manual-review-queue")
    manual_review.add_argument("--creator", required=True)
    manual_review.add_argument("--threadsdash-report-json")
    warmup = sub.add_parser("account-warmup-report")
    warmup.add_argument("--creator", required=True)
    warmup.add_argument("--threadsdash-report-json")
    lifecycle = sub.add_parser("lifecycle-dashboard")
    lifecycle.add_argument("--campaign", required=True)
    lifecycle.add_argument("--user-id")
    lifecycle.add_argument("--threadsdash-posts-json")
    lifecycle.add_argument(
        "--include-threadsdash", choices=["auto", "live", "off"], default="auto"
    )
    creator_surface = sub.add_parser("creator-surface-summary")
    creator_surface.add_argument("--creator", required=True)
    creator_surface.add_argument("--date")
    account_surface = sub.add_parser("account-surface-summary")
    account_surface.add_argument("--creator", required=True)
    account_surface.add_argument("--date")
    account_surface.add_argument("--account-id")
    surface_gap = sub.add_parser("creator-surface-gap-report")
    surface_gap.add_argument("--creator", required=True)
    surface_gap.add_argument("--date")
