// Query-key roots owned by Dashboard V2. Keep this list in sync with mounted
// dashboard tiles so refresh, processing telemetry, and hard-reload
// persistence all describe the same surface.
export const DASHBOARD_QUERY_PREFIXES = [
  'activityEvents',
  'anomalyFeed',
  'audienceWeekdayHour',
  'bioLinkFunnel',
  'competitorSurprises',
  'connectedAccounts',
  'contentMix',
  'fleetHealth',
  'fleetHealthAccounts',
  'fleetKpiData',
  'fleetMetrics',
  'fleetTotals',
  'followerAttribution',
  'ghostPostCount',
  'hookClassLift',
  'linkClickLeaders',
  'liveFirstSixHours',
  'needsAttention',
  'nextUpPosts',
  'nonFollowerReach',
  'overnightBrief',
  'pendingRepliesQueue',
  'postingStreak',
  'qualityByPillar',
  'quoteReplyRatio',
  'reachAnomalies',
  'reelWatchTimeLeaders',
  'replyDepthLeaders',
  'saveRateLeaders',
  'sendsPerReachLeaders',
  'storiesFunnel',
  'storyActivity',
  'storyProfileActivity',
  'strikesCount',
  'systemStatus',
  'threadsPostTotals',
  'vanityAccounts',
  'viewsBySource',
  'watchTimeLeaders',
] as const;
