/**
 * Shared AI fingerprint ban list (Voice Profile Engineering S3.1).
 *
 * Words/phrases that appear ~150x more in AI-generated text than in human
 * writing (FindSkill.ai 2025). Imported by both the autoposter prompt builder
 * (api/_lib/handlers/auto-post/promptBuilder.ts) and the composer's
 * `/ai?action=generate` handler so hand-written and auto-generated posts
 * carry the same anti-AI-tell rules.
 *
 * Keep this file as the single source of truth. Do not duplicate the list
 * inline in any caller.
 */

export const GLOBAL_AI_BANS: readonly string[] = [
	// AI overuse words
	"delve",
	"utilize",
	"leverage",
	"facilitate",
	"underscore",
	"landscape",
	"paradigm",
	"ecosystem",
	"synergy",
	"optimize",
	"streamline",
	"robust",
	"comprehensive",
	"innovative",
	"transformative",
	"noteworthy",
	"invaluable",
	"testament",
	"pivotal",
	"nuanced",
	"multifaceted",
	"holistic",
	"groundbreaking",
	"cutting-edge",
	"game-changer",
	"tapestry",
	// Formal connectives no 19yo uses
	"furthermore",
	"moreover",
	"however",
	"nevertheless",
	"consequently",
	"subsequently",
	"henceforth",
	"notwithstanding",
	"albeit",
	"wherein",
	"thereby",
	"thus",
	"hence",
	"therefore",
	"additionally",
	"accordingly",
	"conversely",
	// AI filler phrases
	"it's worth noting",
	"it's important to",
	"I think it's important",
	"at the end of the day",
	"when it comes to",
	"in terms of",
	"the fact that",
	"needless to say",
	"it goes without saying",
	"that being said",
	// Register violations (no casual 19yo texts these)
	"individuals",
	"approximately",
	"regarding",
	"pertaining",
	"aforementioned",
	"subsequent",
	"preliminary",
	"anticipate",
	"endeavor",
	"commence",
	"substantial",
	"significant",
	"demonstrate",
	"implement",
	"fundamental",
	"perspective",
	"methodology",
	"framework",
	"infrastructure",
	"initiative",
	// Emotional AI-generic (prefer persona-specific alternatives)
	"breathtaking",
	"stunning",
	"mesmerizing",
	"captivating",
	"exquisite",
	"remarkable",
	"extraordinary",
	"phenomenal",
	"magnificent",
	"incredible",
	// Academic hedging (AI default register)
	"arguably",
	"presumably",
	"ostensibly",
	"fundamentally",
	"essentially",
	"inherently",
	"intrinsically",
	"predominantly",
	"particularly",
	"respectively",
	"ultimately",
	"undoubtedly",
	"inevitably",
	"intricately",
	"profoundly",
	// AI transition phrases
	"in essence",
	"in light of",
	"as a result",
	"with respect to",
	"on the other hand",
	"in conclusion",
	"to summarize",
	"as mentioned",
	"it should be noted",
	"it is crucial",
];
