/* This file is generated by scripts/generate-pipeline-contract-schemas.mjs. Do not edit by hand. */

export const generatedPipelineContractSchemas = {
	audioCatalogExport: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "reference_factory.audio_catalog_export.v1",
	  "title": "Reference Factory Audio Catalog Export",
	  "type": "object",
	  "additionalProperties": true,
	  "required": [
	    "schema",
	    "items"
	  ],
	  "properties": {
	    "schema": {
	      "const": "reference_factory.audio_catalog_export.v1"
	    },
	    "exportedAt": {
	      "type": "string"
	    },
	    "items": {
	      "type": "array",
	      "items": {
	        "type": "object",
	        "additionalProperties": true,
	        "required": [
	          "title",
	          "platform"
	        ],
	        "properties": {
	          "title": {
	            "type": "string"
	          },
	          "artistName": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "platform": {
	            "type": "string"
	          },
	          "nativeAudioId": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "nativeAudioUrl": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "moodTags": {
	            "type": "array",
	            "items": {
	              "type": "string"
	            }
	          },
	          "bestContentTypes": {
	            "type": "array",
	            "items": {
	              "type": "string"
	            }
	          },
	          "accountFit": {
	            "type": "array",
	            "items": {
	              "type": "string"
	            }
	          },
	          "trendStatus": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "usageCount": {
	            "type": [
	              "integer",
	              "null"
	            ]
	          },
	          "trendScore": {
	            "type": [
	              "number",
	              "null"
	            ]
	          },
	          "velocityScore": {
	            "type": [
	              "number",
	              "null"
	            ]
	          },
	          "fatigueScore": {
	            "type": [
	              "number",
	              "null"
	            ]
	          },
	          "accountFitScore": {
	            "type": [
	              "number",
	              "null"
	            ]
	          },
	          "creatorFitScore": {
	            "type": [
	              "number",
	              "null"
	            ]
	          },
	          "recommendationConfidence": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "trendSources": {
	            "type": "array",
	            "items": {
	              "type": "string"
	            }
	          },
	          "trendSnapshots": {
	            "type": "array",
	            "items": {
	              "type": "object",
	              "additionalProperties": true
	            }
	          },
	          "exampleReels": {
	            "type": "array",
	            "items": {
	              "type": [
	                "string",
	                "object"
	              ]
	            }
	          },
	          "performanceSummary": {
	            "type": "object",
	            "additionalProperties": true
	          },
	          "fatigue": {
	            "type": "object",
	            "additionalProperties": true
	          },
	          "resolved": {
	            "type": "boolean"
	          },
	          "reviewReasons": {
	            "type": "array",
	            "items": {
	              "type": "string"
	            }
	          },
	          "sourceConfidence": {
	            "type": [
	              "number",
	              "null"
	            ]
	          }
	        }
	      }
	    }
	  }
	} as const,
	audioIntent: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "pipeline.audio_intent.v1",
	  "title": "Pipeline Audio Intent",
	  "type": "object",
	  "additionalProperties": true,
	  "required": [
	    "schema",
	    "mode",
	    "required",
	    "status",
	    "platform",
	    "recommendations",
	    "gates"
	  ],
	  "properties": {
	    "schema": {
	      "const": "pipeline.audio_intent.v1"
	    },
	    "mode": {
	      "type": "string"
	    },
	    "required": {
	      "type": "boolean"
	    },
	    "status": {
	      "type": "string",
	      "enum": [
	        "not_required",
	        "recommended",
	        "needs_operator_selection",
	        "selected",
	        "attached",
	        "verified",
	        "skipped",
	        "blocked",
	        "needs_review",
	        "burned"
	      ]
	    },
	    "platform": {
	      "type": "string"
	    },
	    "surface": {
	      "type": "string"
	    },
	    "recommendations": {
	      "type": "array",
	      "items": {
	        "type": "object",
	        "additionalProperties": true,
	        "properties": {
	          "audio_title": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "artist_name": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "platform_audio_id": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "platform_url": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "vibe_tags": {
	            "type": "array",
	            "items": {
	              "type": "string"
	            }
	          },
	          "freshness": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "confidence": {
	            "type": [
	              "number",
	              "null"
	            ]
	          },
	          "rationale": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "instruction": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "audioMemoryGraphId": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "trendScore": {
	            "type": [
	              "number",
	              "null"
	            ]
	          },
	          "fatigueScore": {
	            "type": [
	              "number",
	              "null"
	            ]
	          },
	          "accountFitScore": {
	            "type": [
	              "number",
	              "null"
	            ]
	          },
	          "performanceLift": {
	            "type": [
	              "number",
	              "null"
	            ]
	          },
	          "exampleReels": {
	            "type": "array",
	            "items": {
	              "type": [
	                "string",
	                "object"
	              ]
	            }
	          },
	          "selectionRank": {
	            "type": [
	              "integer",
	              "null"
	            ]
	          }
	        }
	      }
	    },
	    "decision": {
	      "type": [
	        "object",
	        "null"
	      ],
	      "additionalProperties": true,
	      "properties": {
	        "schema": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "primaryAudio": {
	          "type": [
	            "object",
	            "null"
	          ],
	          "additionalProperties": true
	        },
	        "backupAudios": {
	          "type": "array",
	          "items": {
	            "type": "object",
	            "additionalProperties": true
	          }
	        },
	        "doNotUseAudios": {
	          "type": "array",
	          "items": {
	            "type": "object",
	            "additionalProperties": true
	          }
	        },
	        "decisionConfidence": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "decisionReasons": {
	          "type": "array",
	          "items": {
	            "type": "string"
	          }
	        },
	        "riskFlags": {
	          "type": "array",
	          "items": {
	            "type": "string"
	          }
	        },
	        "whenToUse": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "whenNotToUse": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "operatorInstruction": {
	          "type": [
	            "string",
	            "null"
	          ]
	        }
	      }
	    },
	    "operator_selection": {
	      "type": [
	        "object",
	        "null"
	      ],
	      "additionalProperties": true,
	      "properties": {
	        "audio_title": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "artist_name": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "platform_audio_id": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "platform_url": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "selected_at": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "selected_by": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "attached_at": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "attached_by": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "verified_at": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "verified_by": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "proof_source": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "proof_url": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "proof_type": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "proof_note": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "proof_captured_at": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "notes": {
	          "type": [
	            "string",
	            "null"
	          ]
	        }
	      }
	    },
	    "task": {
	      "type": [
	        "object",
	        "null"
	      ],
	      "additionalProperties": true,
	      "properties": {
	        "schema": {
	          "const": "pipeline.audio_task.v1"
	        },
	        "status": {
	          "type": "string",
	          "enum": [
	            "open",
	            "selected",
	            "proof_missing",
	            "needs_review",
	            "blocked",
	            "completed",
	            "not_required"
	          ]
	        },
	        "assignee": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "due_at": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "proof_required": {
	          "type": "boolean"
	        },
	        "created_at": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "updated_at": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "completed_at": {
	          "type": [
	            "string",
	            "null"
	          ]
	        }
	      }
	    },
	    "gates": {
	      "type": "object",
	      "additionalProperties": true,
	      "required": [
	        "allow_draft_export",
	        "allow_publish"
	      ],
	      "properties": {
	        "allow_draft_export": {
	          "type": "boolean"
	        },
	        "allow_preview_schedule": {
	          "type": "boolean"
	        },
	        "allow_live_schedule": {
	          "type": "boolean"
	        },
	        "allow_publish": {
	          "type": "boolean"
	        }
	      }
	    },
	    "pipelineTraceId": {
	      "type": [
	        "string",
	        "null"
	      ],
	      "description": "Shared trace ID propagated through the pipeline for end-to-end observability"
	    }
	  }
	} as const,
	campaignDraftPayload: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "campaign_factory.threadsdash_drafts.v1",
	  "title": "Campaign Factory ThreadsDashboard Draft Payload",
	  "type": "object",
	  "additionalProperties": true,
	  "required": [
	    "schema",
	    "campaign",
	    "drafts"
	  ],
	  "properties": {
	    "schema": {
	      "const": "campaign_factory.threadsdash_drafts.v1"
	    },
	    "campaign": {
	      "type": "string"
	    },
	    "userId": {
	      "type": "string"
	    },
	    "drafts": {
	      "type": "array",
	      "items": {
	        "type": "object",
	        "additionalProperties": true,
	        "required": [
	          "platform",
	          "status",
	          "metadata"
	        ],
	        "properties": {
	          "platform": {
	            "type": "string"
	          },
	          "status": {
	            "type": "string"
	          },
	          "distributionSurface": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "metadata": {
	            "type": "object",
	            "required": [
	              "campaign_factory"
	            ],
	            "properties": {
	              "campaign_factory": {
	                "type": "object",
	                "required": [
	                  "asset_state",
	                  "approved",
	                  "captioned_render_present",
	                  "visible_caption_verification",
	                  "expected_visual_verification",
	                  "content_fingerprint",
	                  "generated_asset_lineage",
	                  "captionOutcomeContext",
	                  "audio_intent",
	                  "handoff_manifest",
	                  "readiness_checks_pass",
	                  "visualQcStatus",
	                  "identityVerificationStatus"
	                ],
	                "properties": {
	                  "asset_state": {
	                    "type": "string",
	                    "enum": [
	                      "approved_but_not_publishable",
	                      "publishable_candidate",
	                      "exportable"
	                    ]
	                  },
	                  "approved": {
	                    "type": "boolean"
	                  },
	                  "captioned_render_present": {
	                    "type": "boolean"
	                  },
	                  "visible_caption_verification": {
	                    "type": "string",
	                    "enum": [
	                      "pass",
	                      "fail"
	                    ]
	                  },
	                  "expected_visual_verification": {
	                    "type": "string",
	                    "enum": [
	                      "pass",
	                      "fail"
	                    ]
	                  },
	                  "content_fingerprint": {
	                    "type": "string"
	                  },
	                  "publishability_failure_reasons": {
	                    "type": "array",
	                    "items": {
	                      "type": "string",
	                      "enum": [
	                        "missing_burned_captions",
	                        "wrong_visual",
	                        "missing_caption_hash",
	                        "missing_caption_outcome_context",
	                        "missing_content_fingerprint",
	                        "missing_audio",
	                        "readiness_failed",
	                        "not_approved",
	                        "caption_placement_qc_failed",
	                        "missing_instagram_post_caption",
	                        "instagram_post_caption_quality_failed",
	                        "visual_qc_unavailable",
	                        "visual_qc_failed",
	                        "identity_verification_unavailable",
	                        "identity_verification_failed"
	                      ]
	                    }
	                  },
	                  "blockingReason": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "rootCause": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "handoff_manifest": {
	                    "type": [
	                      "object",
	                      "null"
	                    ],
	                    "required": [
	                      "manifest_version",
	                      "asset_id",
	                      "render_file_id",
	                      "content_fingerprint",
	                      "caption_hash",
	                      "captionOutcomeContext",
	                      "visual_verification_id",
	                      "caption_verification_id",
	                      "audio_id",
	                      "distribution_plan_id",
	                      "exported_by_system",
	                      "exported_at"
	                    ],
	                    "properties": {
	                      "manifest_version": {
	                        "enum": [
	                          1,
	                          2
	                        ]
	                      },
	                      "asset_id": {
	                        "type": "string"
	                      },
	                      "render_file_id": {
	                        "type": "string"
	                      },
	                      "content_fingerprint": {
	                        "type": "string"
	                      },
	                      "caption_hash": {
	                        "type": "string"
	                      },
	                      "captionOutcomeContext": {
	                        "$ref": "caption_outcome_context.v1.schema.json"
	                      },
	                      "visual_verification_id": {
	                        "type": "string"
	                      },
	                      "caption_verification_id": {
	                        "type": "string"
	                      },
	                      "audio_id": {
	                        "type": "string"
	                      },
	                      "distribution_plan_id": {
	                        "type": "string"
	                      },
	                      "exported_by_system": {
	                        "const": "campaign_factory"
	                      },
	                      "exported_at": {
	                        "type": "string"
	                      },
	                      "concept_id": {
	                        "type": "string"
	                      },
	                      "parent_asset_id": {
	                        "type": "string"
	                      },
	                      "parent_reel_id": {
	                        "type": "string"
	                      },
	                      "variant_family_id": {
	                        "type": "string"
	                      },
	                      "variant_id": {
	                        "type": "string"
	                      },
	                      "variant_index": {
	                        "type": "integer"
	                      },
	                      "variant_operations": {
	                        "type": "array"
	                      },
	                      "visualQcStatus": {
	                        "type": "string",
	                        "enum": [
	                          "passed",
	                          "failed",
	                          "unavailable"
	                        ]
	                      },
	                      "identityVerificationStatus": {
	                        "type": "string",
	                        "enum": [
	                          "passed",
	                          "failed",
	                          "unavailable"
	                        ]
	                      },
	                      "visualQc": {
	                        "type": "object",
	                        "additionalProperties": true
	                      },
	                      "identityVerification": {
	                        "type": "object",
	                        "additionalProperties": true
	                      }
	                    },
	                    "additionalProperties": true
	                  },
	                  "concept_id": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "parent_asset_id": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "parent_reel_id": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "variant_family_id": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "variant_id": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "variant_index": {
	                    "type": [
	                      "integer",
	                      "null"
	                    ]
	                  },
	                  "variant_operations": {
	                    "type": [
	                      "array",
	                      "null"
	                    ]
	                  },
	                  "readiness_checks_pass": {
	                    "type": "boolean"
	                  },
	                  "graph_id": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "campaign_graph_id": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "source_asset_graph_id": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "rendered_asset_graph_id": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "audit_graph_id": {
	                    "type": [
	                      "string",
	                      "null"
	                    ]
	                  },
	                  "captionOutcomeContext": {
	                    "$ref": "caption_outcome_context.v1.schema.json"
	                  },
	                  "caption_outcome_context": {
	                    "$ref": "caption_outcome_context.v1.schema.json"
	                  },
	                  "generated_asset_lineage": {
	                    "$ref": "generated_asset_lineage.v1.schema.json"
	                  },
	                  "audio_intent": {
	                    "$ref": "audio_intent.v1.schema.json"
	                  },
	                  "visualQcStatus": {
	                    "type": "string",
	                    "enum": [
	                      "passed",
	                      "failed",
	                      "unavailable"
	                    ]
	                  },
	                  "identityVerificationStatus": {
	                    "type": "string",
	                    "enum": [
	                      "passed",
	                      "failed",
	                      "unavailable"
	                    ]
	                  }
	                },
	                "additionalProperties": true
	              }
	            },
	            "additionalProperties": true
	          }
	        }
	      }
	    },
	    "pipelineTraceId": {
	      "type": [
	        "string",
	        "null"
	      ],
	      "description": "Shared trace ID propagated through the pipeline for end-to-end observability"
	    }
	  }
	} as const,
	captionOutcomeContext: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "campaign_factory.caption_outcome_context.v1",
	  "title": "Campaign Factory Caption Outcome Context",
	  "type": "object",
	  "additionalProperties": true,
	  "required": [
	    "schema"
	  ],
	  "properties": {
	    "schema": {
	      "const": "campaign_factory.caption_outcome_context.v1"
	    },
	    "caption_hash": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "caption_text": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "caption_bank": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "caption_banks": {
	      "type": [
	        "array",
	        "null"
	      ],
	      "items": {
	        "type": "string"
	      }
	    },
	    "creator_mix": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "creator_model": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "frame_type": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "length_class": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "format_class": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "caption_fit_version": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "suitability_decision": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "suitability_reason": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "captionSceneTags": {
	      "type": [
	        "array",
	        "null"
	      ],
	      "items": {
	        "type": "string"
	      }
	    },
	    "reelSceneTags": {
	      "type": [
	        "array",
	        "null"
	      ],
	      "items": {
	        "type": "string"
	      }
	    },
	    "sceneCompatibilityDecision": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "sceneCompatibilityReason": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "captionSceneFitVersion": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "render_recipe": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "source_clip": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "rendered_output": {
	      "type": [
	        "string",
	        "null"
	      ]
	    }
	  }
	} as const,
	creativePlan: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "campaign_factory.creative_plan.v1",
	  "title": "Campaign Factory Creative Plan",
	  "type": "object",
	  "required": [
	    "schema",
	    "id",
	    "name",
	    "platform",
	    "goal",
	    "target_account",
	    "daily_base_video_target",
	    "style_lanes",
	    "model_profile",
	    "source_accounts",
	    "status",
	    "counts",
	    "next_actions"
	  ],
	  "properties": {
	    "schema": {
	      "const": "campaign_factory.creative_plan.v1"
	    },
	    "id": {
	      "type": "string"
	    },
	    "name": {
	      "type": "string"
	    },
	    "platform": {
	      "type": "string"
	    },
	    "goal": {
	      "type": "string"
	    },
	    "target_account": {
	      "type": "string"
	    },
	    "daily_base_video_target": {
	      "type": "integer"
	    },
	    "style_lanes": {
	      "type": "array",
	      "items": {
	        "type": "string"
	      }
	    },
	    "model_profile": {
	      "type": "string"
	    },
	    "source_accounts": {
	      "type": "array",
	      "items": {
	        "type": "string"
	      }
	    },
	    "status": {
	      "type": "string",
	      "enum": [
	        "planned",
	        "references_selected",
	        "prompts_ready",
	        "generated",
	        "ingested",
	        "rendered",
	        "audited",
	        "reviewed",
	        "exported",
	        "posted",
	        "measured"
	      ]
	    },
	    "counts": {
	      "type": "object",
	      "required": [
	        "references",
	        "analyses",
	        "image_prompts",
	        "video_prompts",
	        "generated_videos",
	        "ingested_videos",
	        "rendered_outputs",
	        "reviewed_outputs",
	        "exported_drafts",
	        "posted_items",
	        "measured_items"
	      ],
	      "properties": {
	        "references": {
	          "type": "integer"
	        },
	        "analyses": {
	          "type": "integer"
	        },
	        "image_prompts": {
	          "type": "integer"
	        },
	        "video_prompts": {
	          "type": "integer"
	        },
	        "generated_videos": {
	          "type": "integer"
	        },
	        "ingested_videos": {
	          "type": "integer"
	        },
	        "rendered_outputs": {
	          "type": "integer"
	        },
	        "reviewed_outputs": {
	          "type": "integer"
	        },
	        "exported_drafts": {
	          "type": "integer"
	        },
	        "posted_items": {
	          "type": "integer"
	        },
	        "measured_items": {
	          "type": "integer"
	        }
	      }
	    },
	    "next_actions": {
	      "type": "array",
	      "items": {
	        "type": "string"
	      }
	    },
	    "linked_campaign": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "created_at": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "updated_at": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "pipelineTraceId": {
	      "type": [
	        "string",
	        "null"
	      ],
	      "description": "Shared trace ID propagated through the pipeline for end-to-end observability"
	    }
	  }
	} as const,
	frontGenerationPlan: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "campaign_factory.front_generation_plan.v1",
	  "title": "Campaign Factory Front Generation Plan",
	  "type": "object",
	  "additionalProperties": false,
	  "required": [
	    "schema",
	    "campaign",
	    "referenceImagePath",
	    "soul",
	    "animationMode",
	    "dryRun",
	    "paidGenerationEnabled",
	    "projectedCostUsd",
	    "budgetCapUsd",
	    "budgetStatus",
	    "humanReviewRequired",
	    "publishingAllowed",
	    "stages"
	  ],
	  "properties": {
	    "schema": {
	      "const": "campaign_factory.front_generation_plan.v1"
	    },
	    "campaign": {
	      "type": "string",
	      "minLength": 1
	    },
	    "referenceImagePath": {
	      "type": "string",
	      "minLength": 1
	    },
	    "soul": {
	      "type": "object",
	      "additionalProperties": false,
	      "required": [
	        "creator",
	        "soulId",
	        "soulName"
	      ],
	      "properties": {
	        "creator": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "soulId": {
	          "type": [
	            "string",
	            "null"
	          ]
	        },
	        "soulName": {
	          "type": [
	            "string",
	            "null"
	          ]
	        }
	      }
	    },
	    "animationMode": {
	      "type": "string",
	      "enum": [
	        "kling",
	        "motion_edit"
	      ]
	    },
	    "dryRun": {
	      "type": "boolean"
	    },
	    "paidGenerationEnabled": {
	      "type": "boolean"
	    },
	    "projectedCostUsd": {
	      "type": "number",
	      "minimum": 0
	    },
	    "budgetCapUsd": {
	      "type": [
	        "number",
	        "null"
	      ],
	      "minimum": 0
	    },
	    "budgetStatus": {
	      "type": "string",
	      "enum": [
	        "within_cap",
	        "missing_cap",
	        "exceeds_cap",
	        "not_required"
	      ]
	    },
	    "humanReviewRequired": {
	      "const": true
	    },
	    "publishingAllowed": {
	      "const": false
	    },
	    "stages": {
	      "type": "array",
	      "minItems": 1,
	      "items": {
	        "type": "object",
	        "additionalProperties": false,
	        "required": [
	          "name",
	          "status",
	          "paid",
	          "estimatedCostUsd",
	          "commands"
	        ],
	        "properties": {
	          "name": {
	            "type": "string",
	            "enum": [
	              "soul_reference_image",
	              "still_accept_gate",
	              "kling_video",
	              "motion_edit",
	              "variation"
	            ]
	          },
	          "status": {
	            "type": "string",
	            "enum": [
	              "planned",
	              "blocked",
	              "skipped",
	              "submitted",
	              "waiting_for_review"
	            ]
	          },
	          "paid": {
	            "type": "boolean"
	          },
	          "estimatedCostUsd": {
	            "type": "number",
	            "minimum": 0
	          },
	          "commands": {
	            "type": "array",
	            "items": {
	              "type": "array",
	              "items": {
	                "type": "string"
	              }
	            }
	          },
	          "result": {
	            "type": "object"
	          },
	          "reason": {
	            "type": "string"
	          }
	        }
	      }
	    }
	  }
	} as const,
	generatedAssetLineage: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "campaign_factory.generated_asset_lineage.v1",
	  "title": "Campaign Factory Generated Asset Lineage",
	  "type": "object",
	  "required": [
	    "schema",
	    "pipelineTraceId",
	    "source",
	    "generation",
	    "review"
	  ],
	  "properties": {
	    "schema": {
	      "const": "campaign_factory.generated_asset_lineage.v1"
	    },
	    "source": {
	      "type": "object"
	    },
	    "generation": {
	      "type": "object"
	    },
	    "review": {
	      "type": "object"
	    },
	    "quality": {
	      "type": "object"
	    },
	    "asset_state": {
	      "type": "string",
	      "enum": [
	        "approved_but_not_publishable",
	        "publishable_candidate",
	        "exportable",
	        "invalid_retired_draft"
	      ]
	    },
	    "publishability_failure_reasons": {
	      "type": "array"
	    },
	    "blockingReason": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "rootCause": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "captionOutcomeContext": {
	      "$ref": "caption_outcome_context.v1.schema.json"
	    },
	    "pipelineTraceId": {
	      "type": "string",
	      "minLength": 1,
	      "description": "Shared trace ID propagated through the pipeline for end-to-end observability"
	    }
	  }
	} as const,
	higgsfieldSoulImagePrompt: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "reference_factory.higgsfield_soul_image_prompt.v1",
	  "title": "Higgsfield Soul ID Image Prompt",
	  "type": "object",
	  "required": [
	    "schema",
	    "tool",
	    "status",
	    "sourceReferenceId",
	    "sourcePatternId",
	    "modelProfile",
	    "mainPrompt",
	    "negativePrompt",
	    "closenessControls"
	  ],
	  "properties": {
	    "schema": {
	      "const": "reference_factory.higgsfield_soul_image_prompt.v1"
	    },
	    "tool": {
	      "const": "higgsfield_soul_image"
	    },
	    "status": {
	      "type": "string"
	    },
	    "sourceReferenceId": {
	      "type": "string"
	    },
	    "sourcePatternId": {
	      "type": "string"
	    },
	    "modelProfile": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "mainPrompt": {
	      "type": "string"
	    },
	    "negativePrompt": {
	      "type": "string"
	    },
	    "closenessControls": {
	      "type": "object"
	    },
	    "formatCard": {
	      "type": "object"
	    },
	    "aspectRatio": {
	      "type": "string"
	    },
	    "reviewNotes": {
	      "type": "array"
	    }
	  }
	} as const,
	kling3VideoPrompt: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "reference_factory.kling_3_video_prompt.v1",
	  "title": "Kling 3 Video Prompt",
	  "type": "object",
	  "required": [
	    "schema",
	    "tool",
	    "status",
	    "sourceReferenceId",
	    "sourcePatternId",
	    "modelProfile",
	    "firstFrameInstruction",
	    "mainPrompt",
	    "negativePrompt",
	    "closenessControls"
	  ],
	  "properties": {
	    "schema": {
	      "const": "reference_factory.kling_3_video_prompt.v1"
	    },
	    "tool": {
	      "const": "kling_3_video"
	    },
	    "status": {
	      "type": "string"
	    },
	    "sourceReferenceId": {
	      "type": "string"
	    },
	    "sourcePatternId": {
	      "type": "string"
	    },
	    "modelProfile": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "firstFrameInstruction": {
	      "type": "string"
	    },
	    "mainPrompt": {
	      "type": "string"
	    },
	    "negativePrompt": {
	      "type": "string"
	    },
	    "closenessControls": {
	      "type": "object"
	    },
	    "scenes": {
	      "type": "array"
	    },
	    "aspectRatio": {
	      "type": "string"
	    },
	    "reviewNotes": {
	      "type": "array"
	    }
	  }
	} as const,
	motionEditRender: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "reel_factory.motion_edit_render.v1",
	  "title": "Reel Factory Motion Edit Render",
	  "type": "object",
	  "additionalProperties": false,
	  "required": [
	    "schema",
	    "animationMode",
	    "paidGeneration",
	    "estimatedCostUsd",
	    "stillPath",
	    "outputPath",
	    "durationSeconds",
	    "caption",
	    "audioIntentPath",
	    "lineagePath",
	    "quality",
	    "ffmpegCommand"
	  ],
	  "properties": {
	    "schema": {
	      "const": "reel_factory.motion_edit_render.v1"
	    },
	    "animationMode": {
	      "const": "motion_edit"
	    },
	    "paidGeneration": {
	      "const": false
	    },
	    "estimatedCostUsd": {
	      "const": 0
	    },
	    "stillPath": {
	      "type": "string",
	      "minLength": 1
	    },
	    "outputPath": {
	      "type": "string",
	      "minLength": 1
	    },
	    "durationSeconds": {
	      "type": "number",
	      "exclusiveMinimum": 0,
	      "maximum": 60
	    },
	    "caption": {
	      "type": "string"
	    },
	    "audioIntentPath": {
	      "type": "string",
	      "minLength": 1
	    },
	    "lineagePath": {
	      "type": "string",
	      "minLength": 1
	    },
	    "quality": {
	      "type": "object",
	      "additionalProperties": false,
	      "required": [
	        "status",
	        "width",
	        "height",
	        "fps",
	        "durationSeconds"
	      ],
	      "properties": {
	        "status": {
	          "type": "string",
	          "enum": [
	            "planned",
	            "passed",
	            "failed"
	          ]
	        },
	        "width": {
	          "type": "integer",
	          "minimum": 1
	        },
	        "height": {
	          "type": "integer",
	          "minimum": 1
	        },
	        "fps": {
	          "type": "number",
	          "exclusiveMinimum": 0
	        },
	        "durationSeconds": {
	          "type": "number",
	          "exclusiveMinimum": 0
	        },
	        "warnings": {
	          "type": "array",
	          "items": {
	            "type": "string"
	          }
	        }
	      }
	    },
	    "ffmpegCommand": {
	      "type": "array",
	      "items": {
	        "type": "string"
	      }
	    },
	    "dryRun": {
	      "type": "boolean"
	    }
	  }
	} as const,
	patternCard: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "reference_factory.pattern_card.v1",
	  "title": "Reference Factory Viral Pattern Card",
	  "type": "object",
	  "required": [
	    "schema",
	    "id",
	    "platform",
	    "source",
	    "formatType",
	    "hookType",
	    "visualPattern",
	    "shotSequence",
	    "cameraStyle",
	    "subjectAction",
	    "textOverlayStyle",
	    "pacing",
	    "audioVibe",
	    "reuseRisk",
	    "copyRiskNotes",
	    "transformationInstructions"
	  ],
	  "properties": {
	    "schema": {
	      "const": "reference_factory.pattern_card.v1"
	    },
	    "id": {
	      "type": "string"
	    },
	    "platform": {
	      "type": "string"
	    },
	    "source": {
	      "type": "object"
	    },
	    "formatType": {
	      "type": "string"
	    },
	    "hookType": {
	      "type": "string"
	    },
	    "visualPattern": {
	      "type": "string"
	    },
	    "shotSequence": {
	      "type": "array"
	    },
	    "cameraStyle": {
	      "type": "object"
	    },
	    "subjectAction": {
	      "type": "string"
	    },
	    "textOverlayStyle": {
	      "type": "object"
	    },
	    "pacing": {
	      "type": "object"
	    },
	    "audioVibe": {
	      "type": "object"
	    },
	    "ctaPattern": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "reuseRisk": {
	      "type": "string",
	      "enum": [
	        "low",
	        "medium",
	        "high"
	      ]
	    },
	    "copyRiskNotes": {
	      "type": "array"
	    },
	    "transformationInstructions": {
	      "type": "array"
	    },
	    "viralityMetrics": {
	      "type": "object"
	    },
	    "qualityWarnings": {
	      "type": "array"
	    }
	  }
	} as const,
	performanceSync: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "campaign_factory.performance_sync.v1",
	  "title": "Campaign Factory Performance Sync",
	  "type": "object",
	  "additionalProperties": true,
	  "required": [
	    "schema",
	    "campaign",
	    "userId",
	    "pipelineJobId",
	    "pipelineTraceId",
	    "summary"
	  ],
	  "properties": {
	    "schema": {
	      "const": "campaign_factory.performance_sync.v1"
	    },
	    "campaign": {
	      "type": "string"
	    },
	    "userId": {
	      "type": "string"
	    },
	    "checkedAt": {
	      "type": "string"
	    },
	    "postsScanned": {
	      "type": "integer"
	    },
	    "campaignFactoryPostsScanned": {
	      "type": "integer"
	    },
	    "metricHistoryRowsScanned": {
	      "type": "integer",
	      "description": "Rows read from ThreadsDashboard post_metric_history for time-series performance learning"
	    },
	    "campaignFactorySnapshotsScanned": {
	      "type": "integer",
	      "description": "Eligible Campaign Factory performance snapshots considered after expanding post_metric_history"
	    },
	    "inserted": {
	      "type": "integer"
	    },
	    "skipped": {
	      "type": "integer"
	    },
	    "summary": {
	      "type": "object"
	    },
	    "pipelineJobId": {
	      "type": "string",
	      "minLength": 1
	    },
	    "pipelineTraceId": {
	      "type": "string",
	      "minLength": 1,
	      "description": "Shared trace ID propagated through the pipeline for end-to-end observability"
	    }
	  }
	} as const,
	postMetricHistoryRead: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "threadsdashboard.post_metric_history.read.v1",
	  "title": "ThreadsDashboard Post Metric History Read",
	  "type": "object",
	  "additionalProperties": false,
	  "required": [
	    "schema",
	    "rows"
	  ],
	  "properties": {
	    "schema": {
	      "const": "threadsdashboard.post_metric_history.read.v1"
	    },
	    "rows": {
	      "type": "array",
	      "items": {
	        "type": "object",
	        "additionalProperties": true,
	        "required": [
	          "id",
	          "post_id",
	          "account_id",
	          "platform",
	          "snapshot_at",
	          "hours_since_publish",
	          "views_count",
	          "likes_count",
	          "replies_count",
	          "reposts_count",
	          "quotes_count",
	          "shares_count",
	          "saves_count",
	          "reach",
	          "engagement_rate",
	          "created_at"
	        ],
	        "properties": {
	          "id": {
	            "type": "string",
	            "minLength": 1
	          },
	          "post_id": {
	            "type": "string",
	            "minLength": 1
	          },
	          "account_id": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "platform": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "snapshot_at": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "hours_since_publish": {
	            "type": [
	              "number",
	              "integer",
	              "null"
	            ]
	          },
	          "views_count": {
	            "type": [
	              "integer",
	              "null"
	            ]
	          },
	          "likes_count": {
	            "type": [
	              "integer",
	              "null"
	            ]
	          },
	          "replies_count": {
	            "type": [
	              "integer",
	              "null"
	            ]
	          },
	          "reposts_count": {
	            "type": [
	              "integer",
	              "null"
	            ]
	          },
	          "quotes_count": {
	            "type": [
	              "integer",
	              "null"
	            ]
	          },
	          "shares_count": {
	            "type": [
	              "integer",
	              "null"
	            ]
	          },
	          "saves_count": {
	            "type": [
	              "integer",
	              "null"
	            ]
	          },
	          "reach": {
	            "type": [
	              "integer",
	              "null"
	            ]
	          },
	          "engagement_rate": {
	            "type": [
	              "number",
	              "integer",
	              "null"
	            ]
	          },
	          "created_at": {
	            "type": [
	              "string",
	              "null"
	            ]
	          }
	        }
	      }
	    }
	  }
	} as const,
	recommendationAccuracyReport: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "campaign_factory.recommendation_accuracy_report.v1",
	  "title": "Campaign Factory Recommendation Accuracy Report",
	  "type": "object",
	  "required": [
	    "schema",
	    "campaign",
	    "campaignGraphId",
	    "reportId",
	    "reportGraphId",
	    "windowDays",
	    "generatedAt",
	    "recommendationTrustScore",
	    "trustConfidence",
	    "overall",
	    "calibration",
	    "segments",
	    "drift"
	  ],
	  "properties": {
	    "schema": {
	      "const": "campaign_factory.recommendation_accuracy_report.v1"
	    },
	    "campaign": {
	      "type": "string"
	    },
	    "campaignGraphId": {
	      "type": "string",
	      "minLength": 1
	    },
	    "account": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "windowDays": {
	      "type": "integer"
	    },
	    "generatedAt": {
	      "type": "string"
	    },
	    "reportId": {
	      "type": "string",
	      "minLength": 1
	    },
	    "reportGraphId": {
	      "type": "string",
	      "minLength": 1
	    },
	    "recommendationTrustScore": {
	      "type": "integer"
	    },
	    "trustConfidence": {
	      "type": "string",
	      "enum": [
	        "insufficient",
	        "directional",
	        "usable",
	        "strong"
	      ]
	    },
	    "overall": {
	      "type": "object",
	      "required": [
	        "measuredCount",
	        "provedCount",
	        "disprovedCount",
	        "inconclusiveCount",
	        "accuracyDenominator",
	        "accuracyRate"
	      ],
	      "properties": {
	        "measuredCount": {
	          "type": "integer"
	        },
	        "provedCount": {
	          "type": "integer"
	        },
	        "disprovedCount": {
	          "type": "integer"
	        },
	        "inconclusiveCount": {
	          "type": "integer"
	        },
	        "accuracyDenominator": {
	          "type": "integer"
	        },
	        "accuracyRate": {
	          "type": [
	            "number",
	            "null"
	          ]
	        },
	        "averageLift": {
	          "type": [
	            "number",
	            "null"
	          ]
	        }
	      }
	    },
	    "calibration": {
	      "type": "array",
	      "items": {
	        "type": "object"
	      }
	    },
	    "segments": {
	      "type": "object"
	    },
	    "drift": {
	      "type": "array",
	      "items": {
	        "type": "object"
	      }
	    },
	    "observations": {
	      "type": "array",
	      "items": {
	        "type": "object"
	      }
	    },
	    "warnings": {
	      "type": "array",
	      "items": {
	        "type": "string"
	      }
	    }
	  }
	} as const,
	recommendationNextBatch: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "campaign_factory.recommendations.next_batch.v1",
	  "title": "Campaign Factory Next Batch Recommendations",
	  "type": "object",
	  "required": [
	    "schema",
	    "campaign",
	    "campaignGraphId",
	    "persisted",
	    "scoringVersion",
	    "generatedAt",
	    "count",
	    "requestedCount",
	    "inputHash",
	    "items"
	  ],
	  "properties": {
	    "schema": {
	      "const": "campaign_factory.recommendations.next_batch.v1"
	    },
	    "campaign": {
	      "type": "string"
	    },
	    "campaignGraphId": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "runId": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "runGraphId": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "persisted": {
	      "type": "boolean"
	    },
	    "scoringVersion": {
	      "type": "string"
	    },
	    "generatedAt": {
	      "type": "string"
	    },
	    "count": {
	      "type": "integer"
	    },
	    "requestedCount": {
	      "type": "integer"
	    },
	    "account": {
	      "type": [
	        "string",
	        "null"
	      ]
	    },
	    "inputHash": {
	      "type": "string"
	    },
	    "warnings": {
	      "type": "array",
	      "items": {
	        "type": "string"
	      }
	    },
	    "items": {
	      "type": "array",
	      "items": {
	        "type": "object",
	        "required": [
	          "recommendationId",
	          "recommendationGraphId",
	          "status",
	          "campaignGraphId",
	          "rank",
	          "score",
	          "confidence",
	          "reasons",
	          "risks",
	          "scoreBreakdown",
	          "graphEvidence"
	        ],
	        "properties": {
	          "recommendationId": {
	            "type": "string"
	          },
	          "recommendationGraphId": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "status": {
	            "type": "string",
	            "enum": [
	              "proposed",
	              "accepted",
	              "rejected",
	              "executed",
	              "posted",
	              "measured",
	              "proved",
	              "disproved"
	            ]
	          },
	          "campaignGraphId": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "referencePatternGraphId": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "sourceAssetGraphId": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "renderedAssetGraphId": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "rank": {
	            "type": "integer"
	          },
	          "score": {
	            "type": "integer"
	          },
	          "confidence": {
	            "type": "string",
	            "enum": [
	              "low",
	              "medium",
	              "high"
	            ]
	          },
	          "confidenceReason": {
	            "type": "string"
	          },
	          "targetAccount": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "renderedAssetId": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "filename": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "referencePatternId": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "referencePattern": {
	            "type": [
	              "object",
	              "null"
	            ]
	          },
	          "referencePatternEvidence": {
	            "type": "object"
	          },
	          "recommendedVariationPreset": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "variationPresetEvidence": {
	            "type": "object"
	          },
	          "suggestedRecipe": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "hookGuidance": {
	            "type": "string"
	          },
	          "captionGuidance": {
	            "type": "string"
	          },
	          "reasons": {
	            "type": "array",
	            "items": {
	              "type": "string"
	            }
	          },
	          "risks": {
	            "type": "array",
	            "items": {
	              "type": "string"
	            }
	          },
	          "scoreBreakdown": {
	            "type": "object"
	          },
	          "evidence": {
	            "type": "object"
	          },
	          "dataQuality": {
	            "type": "object"
	          },
	          "decision": {
	            "type": "object"
	          },
	          "outcome": {
	            "type": "object"
	          },
	          "baseline": {
	            "type": "object"
	          },
	          "measurementVersion": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "acceptedAt": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "rejectedAt": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "executedAt": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "postedAt": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "measuredAt": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "graphEvidence": {
	            "type": "object"
	          }
	        }
	      }
	    },
	    "pipelineTraceId": {
	      "type": [
	        "string",
	        "null"
	      ],
	      "description": "Shared trace ID propagated through the pipeline for end-to-end observability"
	    }
	  }
	} as const,
	repurposingPlan: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "campaign_factory.repurposing_plan.v1",
	  "type": "object",
	  "additionalProperties": false,
	  "required": [
	    "schema",
	    "master_asset_id",
	    "preset_name",
	    "target_count",
	    "platform"
	  ],
	  "properties": {
	    "schema": {
	      "const": "campaign_factory.repurposing_plan.v1"
	    },
	    "master_asset_id": {
	      "type": "string",
	      "pattern": "^[A-Za-z0-9._:-]+$"
	    },
	    "preset_name": {
	      "type": "string",
	      "enum": [
	        "tiktok_aggressive",
	        "ig_subtle",
	        "custom"
	      ]
	    },
	    "target_count": {
	      "type": "integer",
	      "minimum": 1,
	      "maximum": 500
	    },
	    "platform": {
	      "type": "string"
	    },
	    "custom_config": {
	      "type": "object",
	      "description": "Overrides for the RepurposeConfig if preset_name is custom"
	    }
	  }
	} as const,
	variantAssignment: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "campaign_factory.variant_assignment.v1",
	  "title": "Campaign Factory Variant Assignment",
	  "type": "object",
	  "additionalProperties": false,
	  "required": [
	    "schema",
	    "campaign_slug",
	    "master_asset_id",
	    "master_asset_path",
	    "platform",
	    "generated_at",
	    "assignments"
	  ],
	  "properties": {
	    "schema": {
	      "const": "campaign_factory.variant_assignment.v1"
	    },
	    "campaign_slug": {
	      "type": "string",
	      "minLength": 1
	    },
	    "master_asset_id": {
	      "type": "string",
	      "pattern": "^[A-Za-z0-9._:-]+$"
	    },
	    "master_asset_path": {
	      "type": "string",
	      "minLength": 1
	    },
	    "platform": {
	      "type": "string",
	      "minLength": 1
	    },
	    "generated_at": {
	      "type": "string",
	      "minLength": 1
	    },
	    "variation_enabled": {
	      "type": "boolean"
	    },
	    "assignments": {
	      "type": "array",
	      "minItems": 1,
	      "items": {
	        "type": "object",
	        "additionalProperties": false,
	        "required": [
	          "account_id",
	          "variant_asset_id",
	          "variant_path",
	          "parent_master_asset_id",
	          "preset_name",
	          "distinctness_scores"
	        ],
	        "properties": {
	          "account_id": {
	            "type": "string",
	            "minLength": 1
	          },
	          "instagram_account_id": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "persona": {
	            "type": [
	              "string",
	              "null"
	            ]
	          },
	          "variant_asset_id": {
	            "type": "string",
	            "pattern": "^[A-Za-z0-9._:-]+$"
	          },
	          "variant_path": {
	            "type": "string",
	            "minLength": 1
	          },
	          "parent_master_asset_id": {
	            "type": "string",
	            "pattern": "^[A-Za-z0-9._:-]+$"
	          },
	          "preset_name": {
	            "type": "string",
	            "minLength": 1
	          },
	          "distinctness_scores": {
	            "type": "object",
	            "additionalProperties": false,
	            "required": [
	              "master_ssim",
	              "sibling_max_ssim",
	              "threshold"
	            ],
	            "properties": {
	              "master_ssim": {
	                "type": "number",
	                "minimum": 0,
	                "maximum": 1
	              },
	              "sibling_max_ssim": {
	                "type": "number",
	                "minimum": 0,
	                "maximum": 1
	              },
	              "threshold": {
	                "type": "number",
	                "minimum": 0,
	                "maximum": 1
	              }
	            }
	          },
	          "lineage": {
	            "type": "object"
	          }
	        }
	      }
	    }
	  }
	} as const,
	videoAnalysis: {
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "reference_factory.video_analysis.v1",
	  "title": "Reference Factory Video Analysis",
	  "type": "object",
	  "required": [
	    "schema",
	    "id",
	    "referenceId",
	    "provider",
	    "status",
	    "media",
	    "signals",
	    "patternCard"
	  ],
	  "properties": {
	    "schema": {
	      "const": "reference_factory.video_analysis.v1"
	    },
	    "id": {
	      "type": "string"
	    },
	    "referenceId": {
	      "type": "string"
	    },
	    "provider": {
	      "type": "string"
	    },
	    "status": {
	      "type": "string"
	    },
	    "media": {
	      "type": "object"
	    },
	    "signals": {
	      "type": "object"
	    },
	    "patternCard": {
	      "$ref": "pattern_card.v1.schema.json"
	    },
	    "raw": {
	      "type": "object"
	    }
	  }
	} as const,
} as const;

export const generatedPipelineContractSchemaManifest = [
	{ key: "audioCatalogExport", filename: "audio_catalog_export.v1.schema.json", id: "reference_factory.audio_catalog_export.v1" },
	{ key: "audioIntent", filename: "audio_intent.v1.schema.json", id: "pipeline.audio_intent.v1" },
	{ key: "campaignDraftPayload", filename: "campaign_draft_payload.v1.schema.json", id: "campaign_factory.threadsdash_drafts.v1" },
	{ key: "captionOutcomeContext", filename: "caption_outcome_context.v1.schema.json", id: "campaign_factory.caption_outcome_context.v1" },
	{ key: "creativePlan", filename: "creative_plan.v1.schema.json", id: "campaign_factory.creative_plan.v1" },
	{ key: "frontGenerationPlan", filename: "front_generation_plan.v1.schema.json", id: "campaign_factory.front_generation_plan.v1" },
	{ key: "generatedAssetLineage", filename: "generated_asset_lineage.v1.schema.json", id: "campaign_factory.generated_asset_lineage.v1" },
	{ key: "higgsfieldSoulImagePrompt", filename: "higgsfield_soul_image_prompt.v1.schema.json", id: "reference_factory.higgsfield_soul_image_prompt.v1" },
	{ key: "kling3VideoPrompt", filename: "kling_3_video_prompt.v1.schema.json", id: "reference_factory.kling_3_video_prompt.v1" },
	{ key: "motionEditRender", filename: "motion_edit_render.v1.schema.json", id: "reel_factory.motion_edit_render.v1" },
	{ key: "patternCard", filename: "pattern_card.v1.schema.json", id: "reference_factory.pattern_card.v1" },
	{ key: "performanceSync", filename: "performance_sync.v1.schema.json", id: "campaign_factory.performance_sync.v1" },
	{ key: "postMetricHistoryRead", filename: "post_metric_history.read.v1.schema.json", id: "threadsdashboard.post_metric_history.read.v1" },
	{ key: "recommendationAccuracyReport", filename: "recommendation_accuracy_report.v1.schema.json", id: "campaign_factory.recommendation_accuracy_report.v1" },
	{ key: "recommendationNextBatch", filename: "recommendation_next_batch.v1.schema.json", id: "campaign_factory.recommendations.next_batch.v1" },
	{ key: "repurposingPlan", filename: "repurposing_plan.v1.schema.json", id: "campaign_factory.repurposing_plan.v1" },
	{ key: "variantAssignment", filename: "variant_assignment.v1.schema.json", id: "campaign_factory.variant_assignment.v1" },
	{ key: "videoAnalysis", filename: "video_analysis.v1.schema.json", id: "reference_factory.video_analysis.v1" },
] as const;
